#!/bin/sh
export LANG=zh_CN.UTF-8
if [ "$1" = "sync" ];then
    scp -i ~/router -r ./index.html  ./static/ root@router:/web/
else
    npm run html
    uglifyjs --no-copyright ./src/lib/js/canvas-nest.js > ./static/js/canvas-nest.min.js 
    cleancss ./static/css/web.i.css ./src/css/master.css   --s0 > ./static/css/web.css
    uglifyjs --no-copyright ./static/js/web.i.js ./src/js/commit.dev.js ./static/js/canvas-nest.min.js ./src/js/init.js > ./static/js/web.js
    timestamp=$(date '+%s')
    sed -i "s/date_time=\"[0-9]*\"/date_time=\"$timestamp\"/g" ./index.html
    sed -i "s/web.js?t=[0-9]*/web.js?t=$timestamp/g" ./*.html
    sed -i "s/web.css?t=[0-9]*/web.css?t=$timestamp/g" ./*.html
    #生成时间戳保存到version.txt
    echo $(date -d @$timestamp) > ./static/text/version.txt
    #cd ..
    #taesync -local C:\Users\hiqfs\git\tat.conf.properties
    echo 执行完毕
    echo "代码生成时间: "$(date -d @$timestamp)
fi