#!/bin/sh
export LANG=zh_CN.UTF-8
npm run html
#uglifyjs --no-copyright ./src/lib/js/canvas-nest.js > ./static/js/canvas-nest.min.js 
cleancss ./static/css/web.i.css ./src/css/master.css   --s0 > ./static/css/web.css
uglifyjs ./src/lib/js/canvas-nest.js > ./static/js/canvas-nest.min.js 
echo "api=$(cat ./src/json/api.json);" > ./static/js/api.js 
file_compressed=(
    ./src/lib/js/jquery.min.js
    ./static/js/web.i.js
    #./static/js/canvas-nest.min.js
    ./static/js/api.js
    #./src/js/back.js
    #./src/js/cache.js   
    ./src/js/commit.dev.js
    ./src/js/init.js
)
uglifyjs  ${file_compressed[@]}> ./static/js/web.js
timestamp=$(date '+%s')
sed -i "s/date_time = \"[0-9]*\"/date_time=\"$timestamp\"/g" ./index.html
sed -i "s/web.js?t=[0-9]*/web.js?t=$timestamp/g" ./*.html
sed -i "s/web.css?t=[0-9]*/web.css?t=$timestamp/g" ./*.html
#生成时间戳保存到version.txt
echo $(date -d @$timestamp) > ./static/text/version.txt
cp src/js/base.js static/js/base.js
#cd ..
#taesync -local C:\Users\hiqfs\git\tat.conf.properties
echo 执行完毕
echo "代码生成时间: "$(date -d @$timestamp)
if [ "$1" = "sync" ];then
    scp -i ~/router -r ./index.html ./Menu.html  ./static/ root@router:/web/
fi